### PR TITLE
Admin interface

### PR DESCRIPTION
**Pull request by kirknorthrop**

### CODE REVIEW

**Comment by inglesp** [comment]
Not sure if you'd like a review from me yet, but have had a quick look and it seems eminently sensible.  Suggest deploying and getting feedback from Daniele.  As far as I can tell, you're not introducing any admin actions yet, but once you do I'd like to see some tests that they do the right thing.

**Comment by kirknorthrop** [comment]
I was mainly putting it up to see how big it was, cause it's a bit of a big PR unfortunately, and also to get Travis to run :D

Yes, I will look to add tests when the actions are in, but most of the actions we will add exist already (eg refund) and so I assume these already have tests from last year - but yes, the action functions called will be tested.

My main concern so far has been getting the permissions right for GDPR purposes. Then adding other things should be trivial.

**Comment by kirknorthrop** [comment]
@inglesp This is ready for review now!

**Comment by evildmp** [comment]
Looks good to me.

**Comment by inglesp** [comment]
Sorry, I missed the review request.

I haven't reviewed in detail but it looks generally sensible, and if Daniele's happy with how it works then I am too.

**Pull request merged**
